name: Build release

on:
  - push

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        job:
          - { os: macos-latest }
          - { os: ubuntu-latest }
          - { os: windows-latest }


    name: Build
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename binary
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            mv target/release/probe-client target/release/probe-client.linux.out
          elif [ "$RUNNER_OS" == "macOS" ]; then
            mv target/release/probe-client target/release/probe-client.macos.out
          fi
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            target/release/probe-client.linux
            target/release/probe-client.macos
            target/release/probe-client.exe